# Generated by Django 5.2.5 on 2025-08-10 20:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, help_text='icon name or url', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='listings.city')),
            ],
            options={
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('sale', 'Satılık'), ('rent', 'Kiralık')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area_m2', models.PositiveIntegerField(blank=True, null=True)),
                ('beds', models.PositiveSmallIntegerField()),
                ('baths', models.PositiveSmallIntegerField()),
                ('toilet', models.PositiveSmallIntegerField()),
                ('balcony', models.PositiveSmallIntegerField()),
                ('rooms', models.CharField(blank=True, help_text='ör. 3+1', max_length=10)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('heating', models.CharField(blank=True, choices=[('none', 'Yok'), ('central', 'Merkezi'), ('individual', 'Kombili'), ('floor', 'Yerden Isıtma')], max_length=30)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('neighborhood', models.CharField(blank=True, max_length=200)),
                ('full_address', models.TextField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='listings.amenity')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='listings.city')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='listings.district')),
                ('features', models.ManyToManyField(blank=True, related_name='properties', to='listings.feature')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='listings.propertytype')),
            ],
            options={
                'indexes': [models.Index(fields=['price'], name='listings_pr_price_ee6360_idx'), models.Index(fields=['listing_type'], name='listings_pr_listing_4ec842_idx'), models.Index(fields=['-created_at'], name='listings_pr_created_e6aabb_idx'), models.Index(fields=['city', 'district'], name='listings_pr_city_id_d8509c_idx')],
            },
        ),
    ]
