# Generated by Django 5.2.5 on 2025-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_propertycategory_remove_property_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Satılık'), ('rent', 'Kiralık')], default='sale', max_length=50),
            preserve_default=False,
        ),
    ]
