# Generated by Django 5.2.5 on 2025-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_feature_listing_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
    ]
